name: Pre-Release
on:
  push:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "BUILD_TIME=$(date -u)"
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "26"
          cache: "pnpm"
      - name: Build & Zip
        working-directory: ./dist
        run: |
          tar cf dist.tar *
          lz4 -0 -k dist.tar
          zstd -10 -k dist.tar
          xz -19e -k dist.tar
          rm -rf index.html assets
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./dist/*
      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*
          name: "!!! PRE-RELEASE !!!"
          tag-name: pre-release
          body: "Build at: ($BUILD_TIME)"
          generate_release_notes: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
